<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\0_number.bmp" />
    <None Remove="Assets\1_number.bmp" />
    <None Remove="Assets\2_number.bmp" />
    <None Remove="Assets\3_number.bmp" />
    <None Remove="Assets\4_number.bmp" />
    <None Remove="Assets\5_number.bmp" />
    <None Remove="Assets\6_number.bmp" />
    <None Remove="Assets\7_number.bmp" />
    <None Remove="Assets\8_number.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\0_number.bmp" />
    <Resource Include="Assets\1_number.bmp" />
    <Resource Include="Assets\2_number.bmp" />
    <Resource Include="Assets\3_number.bmp" />
    <Resource Include="Assets\4_number.bmp" />
    <Resource Include="Assets\5_number.bmp" />
    <Resource Include="Assets\6_number.bmp" />
    <Resource Include="Assets\7_number.bmp" />
    <Resource Include="Assets\8_number.bmp" />
  </ItemGroup>

</Project>
